-- 사용자 테이블
CREATE TABLE users (
    user_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    created_at timestamptz(6) NOT NULL,
    email varchar(255) NOT NULL,
    nickname varchar(255) NOT NULL,
    pass_code varchar(255) NOT NULL,
    updated_at timestamptz(6) NOT NULL,
    user_name varchar(255) NOT NULL,
    withdrawn_flag bool NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

-- 인증 토큰 테이블
CREATE TABLE user_tokens (
    token_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    created_at timestamptz(6) NOT NULL,
    refresh_token varchar(255) NOT NULL,
    user_id int4 NOT NULL,
    CONSTRAINT user_tokens_pkey PRIMARY KEY (token_id)
);

-- 메타마스크 지갑 테이블
CREATE TABLE metamask_wallets (
    wallet_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    created_at timestamptz(6) NOT NULL,
    primary_flag bool NOT NULL,
    updated_at timestamptz(6) NOT NULL,
    wallet_address varchar(255) NOT NULL,
    user_id int4 NOT NULL,
    CONSTRAINT metamask_wallets_pkey PRIMARY KEY (wallet_id)
);

-- 은행 테이블
CREATE TABLE banks (
    bank_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    bank_name varchar(255) NOT NULL,
    CONSTRAINT banks_pkey PRIMARY KEY (bank_id)
);

-- 환불 계좌 테이블
CREATE TABLE refund_accounts (
    refund_account_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    account_number varchar(255) NOT NULL,
    bank_id int4 NOT NULL,
    created_at timestamptz(6) NOT NULL,
    primary_flag bool NOT NULL,
    updated_at timestamptz(6) NOT NULL,
    user_id int4 NOT NULL,
    CONSTRAINT refund_accounts_pkey PRIMARY KEY (refund_account_id)
);

-- 계약 테이블
CREATE TABLE contracts (
    contract_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    contract_date timestamptz(6) NOT NULL,
    contract_status varchar(50) NOT NULL,
    contract_terms varchar(1000) NULL,
    created_at timestamptz(6) NOT NULL,
    default_count int4 NULL,
    default_interest_rate numeric(38, 2) NULL,
    deleted_flag bool NOT NULL,
    early_payment bool NULL,
    encrypted_contract_key varchar(1024) NULL,
    grace_line_days int4 NOT NULL,
    interest_rate numeric(38, 2) NOT NULL,
    key_version int4 NULL,
    loan_amount numeric(38, 2) NOT NULL,
    loan_term int4 NULL,
    maturity_date timestamptz(6) NOT NULL,
    message varchar(500) NULL,
    monthly_payment_date int4 NULL,
    nft_image_url varchar(255) NULL,
    prepayment_interest_rate numeric(38, 2) NULL,
    promissory_note_transferability_flag bool NULL,
    reject_message varchar(500) NULL,
    rejected_at timestamptz(6) NULL,
    repayment_type varchar(50) NOT NULL,
    token_id int8 NULL,
    updated_at timestamptz(6) NULL,
    creditor_id int4 NOT NULL,
    debtor_id int4 NOT NULL,
    CONSTRAINT contracts_pkey PRIMARY KEY (contract_id),
    CONSTRAINT contracts_contract_status_check CHECK (((contract_status)::text = ANY ((ARRAY['REQUESTED'::character varying, 'MODIFICATION_REQUESTED'::character varying, 'CONTRACTED'::character varying, 'CANCELED'::character varying, 'REJECTED'::character varying])::text[]))),
    CONSTRAINT contracts_repayment_type_check CHECK (((repayment_type)::text = ANY ((ARRAY['EPIP'::character varying, 'EPP'::character varying, 'BP'::character varying])::text[])))
);

-- 약속어음 테이블
CREATE TABLE promissory_note (
    token_id int8 NOT NULL,
    acceleration_clause int4 NOT NULL,
    add_terms text NULL,
    add_terms_hash text NULL,
    contract_date date NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    creditor_info_hash varchar(128) NOT NULL,
    creditor_name varchar(255) NOT NULL,
    creditor_sign text NOT NULL,
    creditor_wallet_address varchar(42) NOT NULL,
    debtor_info_hash varchar(128) NOT NULL,
    debtor_name varchar(255) NOT NULL,
    debtor_sign text NOT NULL,
    debtor_wallet_address varchar(42) NOT NULL,
    default_interest_rate int4 NOT NULL,
    deleted_flag bool NOT NULL,
    earlypay_fee int4 NOT NULL,
    earlypay_flag bool NOT NULL,
    interest_rate int4 NOT NULL,
    loan_amount int8 NOT NULL,
    loan_term int4 NOT NULL,
    maturity_date date NOT NULL,
    monthly_payment_date int4 NOT NULL,
    nft_image text NULL,
    repayment_type varchar(50) NOT NULL,
    CONSTRAINT promissory_note_pkey null
);

-- 상환 일정 테이블
CREATE TABLE repayment_schedule (
    token_id numeric(38) NOT NULL,
    acceleration_clause int4 NOT NULL,
    accumulated_overdue_interest int8 NOT NULL,
    active_flag bool NOT NULL,
    created_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    current_interest_rate int4 NOT NULL,
    debtor_wallet_address varchar(42) NOT NULL,
    default_count int4 NOT NULL,
    default_interest_rate int4 NOT NULL,
    fixed_payment_amount int8 NULL,
    initial_principal int8 NOT NULL,
    interest_rate int4 NOT NULL,
    monthly_payment_date int4 NOT NULL,
    next_monthly_payment_date timestamptz(6) NOT NULL,
    overdue_days int4 NOT NULL,
    overdue_flag bool NOT NULL,
    overdue_start_date timestamptz(6) NULL,
    remaining_payments int4 NOT NULL,
    remaining_principal int8 NOT NULL,
    repayment_type varchar(50) NOT NULL,
    total_default_count int4 NOT NULL,
    total_payments int4 NOT NULL,
    updated_at timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT repayment_schedule_pkey PRIMARY KEY (token_id)
);

-- 경매 테이블
CREATE TABLE auctions (
    auction_id int4 GENERATED BY DEFAULT AS IDENTITY( MINVALUE 0 NO MAXVALUE START 0 NO CYCLE) NOT NULL,
    auction_status varchar(50) NOT NULL,
    contract_ipfs_url varchar(255) NULL,
    created_at timestamptz(6) NOT NULL,
    end_date timestamptz(6) NOT NULL,
    minimum_bid int8 NOT NULL,
    price int8 NULL,
    remain_principal int8 NULL,
    remain_repayment_date int4 NULL,
    return_rate numeric(38, 2) NULL,
    seller_sign varchar(255) NOT NULL,
    token_id numeric(38) NOT NULL,
    winning_bidder int4 NULL,
    user_id int4 NOT NULL,
    CONSTRAINT auctions_pkey PRIMARY KEY (auction_id),
    CONSTRAINT auctions_auction_status_check CHECK (((auction_status)::text = ANY ((ARRAY['ING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying, 'CANCELED'::character varying])::text[])))
);

CREATE INDEX idx_auction_status ON auctions (auction_status);

-- 입찰 테이블
CREATE TABLE bids (
    bid_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    bid_amount int8 NOT NULL,
    bidder_sign varchar(255) NOT NULL,
    created_at timestamptz(6) NOT NULL,
    user_id int4 NOT NULL,
    auction_id int4 NOT NULL,
    CONSTRAINT bids_pkey PRIMARY KEY (bid_id)
);

-- 코인 로그 테이블
CREATE TABLE coin_logs (
    coin_log_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    account varchar(255) NOT NULL,
    amount int8 NOT NULL,
    created_at timestamptz(6) NOT NULL,
    order_id varchar(255) NULL,
    payment_key varchar(255) NULL,
    status varchar(255) NULL,
    "type" varchar(255) NOT NULL,
    user_id int4 NOT NULL,
    CONSTRAINT coin_logs_pkey PRIMARY KEY (coin_log_id),
    CONSTRAINT coin_logs_status_check CHECK (((status)::text = ANY ((ARRAY['SUCCESS'::character varying, 'FAIL'::character varying])::text[]))),
    CONSTRAINT coin_logs_type_check CHECK (((type)::text = ANY ((ARRAY['DEPOSIT'::character varying, 'WITHDRAWAL'::character varying])::text[])))
);

-- 알림 테이블
CREATE TABLE notifications (
    notification_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    "content" text NOT NULL,
    created_at timestamptz(6) NULL,
    read_flag bool NOT NULL,
    related_id int4 NULL,
    related_type varchar(50) NULL,
    title varchar(255) NOT NULL,
    "type" varchar(50) NOT NULL,
    updated_at timestamptz(6) NULL,
    user_id int4 NOT NULL,
    CONSTRAINT notifications_pkey PRIMARY KEY (notification_id),
    CONSTRAINT notifications_related_type_check CHECK (((related_type)::text = ANY ((ARRAY['AUCTION'::character varying, 'CONTRACT'::character varying])::text[]))),
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['AUCTION_FAILED'::character varying, 'AUCTION_SUCCESS'::character varying, 'AUCTION_TRANSFERRED'::character varying, 'BID_FAILED'::character varying, 'CONTRACT_REQUESTED'::character varying, 'CONTRACT_COMPLETED'::character varying, 'CONTRACT_MODIFICATION_REQUESTED'::character varying, 'CONTRACT_CANCELED'::character varying])::text[])))
);

-- 공통 코드 테이블
CREATE TABLE common_codes (
    code_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    active_flag bool NOT NULL,
    code varchar(50) NOT NULL,
    code_name varchar(100) NOT NULL,
    code_type varchar(50) NOT NULL,
    created_at timestamptz(6) NOT NULL,
    description varchar(500) NULL,
    display_order int4 NOT NULL,
    updated_at timestamptz(6) NOT NULL,
    CONSTRAINT common_codes_pkey PRIMARY KEY (code_id),
    CONSTRAINT ukt3ercha3wy264p4tweqiool1n UNIQUE (code_type, code)
);

-- 시스템 공통 코드 테이블
CREATE TABLE sys_common_codes (
    code_id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    active_flag bool NOT NULL,
    code varchar(50) NOT NULL,
    code_name varchar(100) NOT NULL,
    code_type varchar(50) NOT NULL,
    created_at timestamptz(6) NOT NULL,
    description varchar(500) NULL,
    display_order int4 NOT NULL,
    updated_at timestamptz(6) NOT NULL,
    CONSTRAINT sys_common_codes_pkey PRIMARY KEY (code_id),
    CONSTRAINT uk4nvmmetih0hil9wps0xearyth UNIQUE (code_type, code)
);

-- SSAFY 계정 테이블
CREATE TABLE ssafy_accounts (
    ssafy_account_id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
    account_no varchar(255) NOT NULL,
    created_at timestamptz(6) NOT NULL,
    email varchar(255) NOT NULL,
    user_key varchar(255) NOT NULL,
    CONSTRAINT ssafy_accounts_pkey PRIMARY KEY (ssafy_account_id)
);