spring:
  data:
# MySQL 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${LOCAL_DB_HOST:localhost}:${LOCAL_DB_PORT:3306}/antswer_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: root
    password: pple250106

  # JPA 설정 추가
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update  # 로컬 환경에서는 validate 권장
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true  # SQL 로그 하이라이팅 활성화