spring:
  # .env import
  data:
# MySQL 설정
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${LOCAL_DB_HOST:localhost}:${LOCAL_DB_PORT:5432}/${LOCAL_DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUniCode=yes&characterEncoding=UTF-8
    username: ${LOCAL_DB_USERNAME}
    password: ${LOCAL_DB_PASSWORD}

  # JPA 설정 추가
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none  # 로컬 환경에서는 validate 권장
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true  # SQL 로그 하이라이팅 활성화